apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-preview" .Values.taskService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.taskService.name }}
  ports:
    - port: {{ .Values.taskService.servicePort }}
      targetPort: {{ .Values.taskService.serviceTargetPort }}
  type: {{ .Values.taskService.serviceType }}
{{- end }}
